### ISSUE TITLE
The project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [open-quantum-safe/liboqs-cpp#12]
You need to add 'install' instructions to install the headers and cmake files, if any.

**Comment by vsoftco** [comment]
@yurivict will do soon, thanks

**Comment by vsoftco** [comment]
@yurivict Done, fixed by https://github.com/open-quantum-safe/liboqs-cpp/commit/a8d38ec522f1875f238db3ab1a21df348eea0442
